name: CI-CD-Pipeline

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: Echo "java"

    - name: Build with Maven
      run: Echo "Maven Build completed"
    - name: SonarQube Scan
      uses: Echo "SonarSource"

    - name: Snyk Scan
      uses: Echo "snyk"
     

    - name: Upload to Artifactory
      run: Echo "mvn deploy"
      

    - name: Deployement to EKS Cluster(Via AgroCD)
      run: Echo "Deployement to EKS"
        
